CREATE TABLE Item (
  Id STRING(MAX) NOT NULL,
  Name STRING(MAX) NOT NULL,
  Price INT64 NOT NULL,
) PRIMARY KEY (Id);

CREATE TABLE Orders (
  Id STRING(MAX) NOT NULL,
  CustomerEmail STRING(MAX) NOT NULL,
  CreatedAt TIMESTAMP NOT NULL,
  UpdatedAt TIMESTAMP NOT NULL,
  CommitedAt TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp=true),
) PRIMARY KEY (Id);

CREATE TABLE OrdersDetail (
  Id STRING(MAX) NOT NULL,
  ItemId STRING(MAX) NOT NULL,
  Price INT64 NOT NULL,
  Count INT64 NOT NULL,
  CreatedAt TIMESTAMP,
  UpdatedAt TIMESTAMP NOT NULL,
  CommitedAt TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp=true),
) PRIMARY KEY (Id, ItemId),
  INTERLEAVE IN PARENT Orders ON DELETE CASCADE;
